### ISSUE TITLE
install not working?

### ISSUE THREAD

**Issue by bmacauley** [uber/assume-role-cli#18]
The install does not seem to work?

go get -u github.com/uber/assume-role-cli

It doesn't seem to install a binary?

**Comment by dansimau** [comment]
The binary is located in `cli/assume-role` so to install it you should do:

```
go get -u github.com/uber/assume-role-cli/cli/assume-role
```

**Comment by dansimau** [comment]
Just fixed the readme. Sorry for the trouble @bmacauley and thanks for bringing it up!
